In [5]:
# import numpy 
import numpy as np 
  
# using Numpy.expand_dims() method 
gfg = np.array([[1, 2], [7, 8]]) 
print(gfg.shape) 
print(gfg) 
print("======================================================")
gfg = np.expand_dims(gfg, axis = 0) 
print(gfg.shape) 
print(gfg) 
print("======================================================")
gfg = np.expand_dims(gfg, axis = 1) 
print(gfg.shape) 
print(gfg) 

print("======================================================")
gfg = np.expand_dims(gfg, axis = -1) 
print(gfg.shape) 
print(gfg) 

(2, 2)
[[1 2]
 [7 8]]
(1, 2, 2)
[[[1 2]
  [7 8]]]
(1, 1, 2, 2)
[[[[1 2]
   [7 8]]]]
(1, 1, 2, 2, 1)
[[[[[1]
    [2]]

   [[7]
    [8]]]]]
